FROM python:3.10.6-buster

WORKDIR /prod

RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN apt-get update -y && apt-get install -y --no-install-recommends build-essential gcc libsndfile1

COPY vocal_patterns vocal_patterns
copy mlops mlops
COPY setup.py setup.py
RUN pip install .

COPY Makefile Makefile
RUN make reset_local_files

CMD uvicorn vocal_patterns.api.simple:app --host 0.0.0.0 --port $PORT
