FROM python:3.10.6-buster

WORKDIR /prod

RUN pip install --upgrade pip
COPY requirements_prod.txt requirements.txt
RUN pip install -r requirements.txt
RUN apt-get update -y && apt-get install -y --no-install-recommends build-essential gcc libsndfile1

COPY vocal_patterns vocal_patterns
COPY setup.py setup.py
RUN pip install .

COPY Makefile Makefile

CMD uvicorn vocal_patterns.api.simple:app --host 0.0.0.0 --port $PORT
